.MODEL SMALL 
.STACK 100H 
.DATA 
DIVIDEND DB 09H      ; Example Dividend = 6
DIVISOR  DB 03H      ; Example Divisor = 2
QUOTIENT DB ? 
REMAINDER DB ? 
MSG1 DB 13,10,"Quotient = $" 
MSG2 DB 13,10,"Remainder = $" 
.CODE 
MAIN PROC 
MOV AX,@DATA 
MOV DS,AX 
MOV AL,DIVIDEND 
MOV BL,DIVISOR 
XOR AH,AH        ; Clear AH for division 
DIV BL           ; AL/BL 
MOV QUOTIENT,AL 
MOV REMAINDER,AH 
; Print Quotient 
LEA DX,MSG1 
MOV AH,09H 
INT 21H 
MOV DL,QUOTIENT 
ADD DL,30H 
MOV AH,02H 
INT 21H 
; Print Remainder 
LEA DX,MSG2 
MOV AH,09H 
INT 21H 
MOV DL,REMAINDER 
ADD DL,30H 
MOV AH,02H 
INT 21H 
MOV AH,4CH 
INT 21H 
MAIN ENDP 
END MAIN